# spring:
  # cloud:
  #   vault:
  #     token: myroot
  #     uri: http://host.docker.internal:8200
  #     kv:
  #       enabled: true
  #       backend: "eshoponcontainers"
  #       application-name: "catalog-api"
  # datasource:    
    # url: "jdbc:sqlserver://${DB_HOST_NAME}:${DB_HOST_PORT};databaseName=${CATALOG_DB_NAME};integratedSecurity=false;encrypt=false;trustServerCertificate=true;"
    # username: sa
    # password: Pass@word
    # driverClassName: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    # url: ${datasource.url}
    # username: ${datasource.username}
    # password: ${datasource.password}
    # driverClassName: "com.microsoft.sqlserver.jdbc.SQLServerDriver"

picBaseUrl: "http://host.docker.internal:5202/catalog-api/api/v1/catalog/items/[0]/pic/"

eventbus:
  host: "localhost"
  username:
  password:
  retryCount: 5
  subscriptionClientName: "Catalog"

#springdoc.swagger-ui.path: /swagger-ui-custom.html
server.port: 9098 
# server.servlet.context-path: /catalog-api
logging:
  level:
    org.springframework.cloud.vault: DEBUG
